name: Auto Sign

on:
  push:
    branches: [ master ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: |
          export NODE_TLS_REJECT_UNAUTHORIZED=0
          yarn config set strict-ssl false
          yarn install --ignore-engines

      - name: Run Sign Script
        env:
          CHAOXING_USERNAME: ${{ secrets.CHAOXING_USERNAME }}
          CHAOXING_PASSWORD: ${{ secrets.CHAOXING_PASSWORD }}
        run: npm start
